# Generated by Django 2.1.7 on 2019-09-03 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=25)),
                ('floor', models.CharField(max_length=25)),
                ('flat_no', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=25)),
                ('address_type', models.CharField(choices=[('NtnlId', 'National ID'), ('BrthCrt', 'Birth certificat'), ('PasPrt', 'Passport')], max_length=25)),
            ],
            options={
                'db_table': 'address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('address', models.ManyToManyField(to='users.Address')),
            ],
            options={
                'db_table': 'contact',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('nationality', models.CharField(blank=True, max_length=256, null=True)),
                ('Arabicname', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'country',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Department_Department',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('child_id', models.ForeignKey(blank=True, db_column='child_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_id', to='users.Department')),
                ('parent_id', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_id', to='users.Department')),
            ],
            options={
                'db_table': 'department_department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('email_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email_server', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'email',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('id_number', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(max_length=250)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('id_type', models.CharField(choices=[('NtnlId', 'National ID'), ('BrthCrt', 'Birth certificat'), ('PasPrt', 'Passport')], max_length=25)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.ForeignKey(db_column='contact_id', on_delete=django.db.models.deletion.CASCADE, to='users.Contact')),
                ('nationality', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Country')),
            ],
            options={
                'db_table': 'identity',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_branch', models.BooleanField(blank=True, db_column='is_branch', null=True)),
                ('address', models.ManyToManyField(to='users.Address')),
                ('email', models.ManyToManyField(to='users.Email')),
                ('nationality', models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Country')),
                ('parent', models.ForeignKey(blank=True, db_column='parent_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organization')),
            ],
            options={
                'db_table': 'organization',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('number1', models.CharField(max_length=25)),
                ('country_code', models.CharField(max_length=5)),
                ('city_code', models.CharField(max_length=3)),
                ('is_active', models.BooleanField(blank=True, db_column='is_active', null=True)),
                ('is_fax', models.BooleanField(blank=True, db_column='is_fax', null=True)),
                ('is_voice', models.BooleanField(blank=True, db_column='is_voice', null=True)),
                ('is_direct', models.BooleanField(blank=True, db_column='is_direct', null=True)),
            ],
            options={
                'db_table': 'phone',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'photo',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.ManyToManyField(to='users.Phone'),
        ),
        migrations.AddField(
            model_name='identity',
            name='photo',
            field=models.ForeignKey(blank=True, db_column='photo_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Photo'),
        ),
        migrations.AddField(
            model_name='department',
            name='email',
            field=models.ManyToManyField(to='users.Email'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ManyToManyField(through='users.Department_Department', to='users.Department'),
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.ManyToManyField(to='users.Email'),
        ),
        migrations.AddField(
            model_name='contact',
            name='nationality',
            field=models.ForeignKey(blank=True, db_column='country_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Country'),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.ManyToManyField(to='users.Phone'),
        ),
    ]
