# Generated by Django 2.1.7 on 2019-09-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190903_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent',
            field=models.ManyToManyField(blank=True, null=True, through='users.Department_Department', to='users.Department'),
        ),
    ]
