# Generated by Django 2.1.4 on 2019-09-05 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190903_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.ManyToManyField(blank=True, null=True, to='users.Email'),
        ),
    ]
