# Generated by Django 2.1.4 on 2019-09-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190905_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='email',
        ),
        migrations.RemoveField(
            model_name='department',
            name='parent',
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, to='users.Address'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.ManyToManyField(blank=True, null=True, to='users.Email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.ManyToManyField(blank=True, null=True, to='users.Phone'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.ManyToManyField(blank=True, null=True, to='users.Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='email',
            field=models.ManyToManyField(blank=True, null=True, to='users.Email'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone',
            field=models.ManyToManyField(blank=True, null=True, to='users.Phone'),
        ),
    ]
