# Generated by Django 2.1.4 on 2019-02-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellgeoinfo',
            name='lat_EG_dd',
            field=models.FloatField(blank=True, db_column='lat_EG_dd', null=True),
        ),
        migrations.AddField(
            model_name='wellgeoinfo',
            name='long_EG_dd',
            field=models.FloatField(blank=True, db_column='long_EG_dd', null=True),
        ),
    ]
