# Generated by Django 2.1.7 on 2019-03-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0002_auto_20190227_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellgeoinfo',
            name='lat_EG_dd',
            field=models.FloatField(blank=True, db_column='lat_eg_dd', null=True),
        ),
        migrations.AlterField(
            model_name='wellgeoinfo',
            name='long_EG_dd',
            field=models.FloatField(blank=True, db_column='long_eg_dd', null=True),
        ),
    ]
