# Generated by Django 2.1.7 on 2019-04-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_wellgeoinfo_meridian_conv_dbl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='meridian_conv_dbl',
        ),
        migrations.AddField(
            model_name='approved',
            name='meridian_conv_dbl',
            field=models.FloatField(blank=True, db_column='meridian_conv_dbl', null=True),
        ),
    ]
