# Generated by Django 2.1.7 on 2019-05-23 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_auto_20190411_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='arabicnameconcession',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='arabicnamewell',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='arguppergrosstotal',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='arguppernettotal',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='argupperporosity',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='boundary400mbuffer',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='chartview',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='concession_txt',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='formationobjectives',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='guardfamilyid',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='left_scale',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='militaryapproval',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='militaryapprovaldate',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='militaryapprovalnumber',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='militarymap100id',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='militarypermitdate',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='militarypermitid',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='militaryrenewpermitdate',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='proposedname',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='prov_rigname',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='prov_spuddate',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='right_scale',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='spuddate_drillseq',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='t_depth',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='well_status_txt',
        ),
        migrations.RemoveField(
            model_name='wellgeoinfo',
            name='well_type_txt',
        ),
    ]
