# Generated by Django 2.1.7 on 2019-05-30 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0007_bindata_seismicventage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bindata',
            name='SeismicVentage',
        ),
    ]
