# Generated by Django 2.1.7 on 2019-05-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0008_remove_bindata_seismicventage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bindata',
            name='seismicid',
            field=models.ForeignKey(blank=True, db_column='seismicid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wells.Seismicvintage'),
        ),
    ]
