# Generated by Django 2.1.7 on 2019-06-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0009_auto_20190530_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisional',
            name='prov_militarypermit',
            field=models.CharField(blank=True, db_column='prov_military_permit', max_length=255, null=True),
        ),
    ]
