# Generated by Django 2.1.7 on 2019-06-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0010_provisional_prov_militarypermit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='st',
            field=models.IntegerField(blank=True, db_column='st_id', null=True),
        ),
    ]
