# Generated by Django 2.1.7 on 2019-06-09 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0011_auto_20190609_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='st',
            field=models.ForeignKey(blank=True, db_column='st_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='wells.Staked'),
        ),
    ]
