# Generated by Django 2.1.7 on 2019-06-10 07:15

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0013_auto_20190609_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='staked',
            name='st_by_array',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=(1, 2), size=None),
        ),
    ]
