# Generated by Django 2.1.7 on 2019-06-10 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0014_staked_st_by_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staked',
            name='st_by_array',
        ),
    ]
