# Generated by Django 2.1.7 on 2019-06-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0015_remove_staked_st_by_array'),
    ]

    operations = [
        migrations.AddField(
            model_name='staked',
            name='st_by_mm',
            field=models.ManyToManyField(related_name='persons_stake_by', to='wells.Persons'),
        ),
    ]
