# Generated by Django 2.1.7 on 2019-06-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0016_staked_st_by_mm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checked',
            name='chk_by',
        ),
        migrations.AddField(
            model_name='checked',
            name='chk_by',
            field=models.ManyToManyField(related_name='persons_checked_by', to='wells.Persons'),
        ),
    ]
