# Generated by Django 2.1.7 on 2019-07-31 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approved',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='bindata',
            options={'managed': True, 'verbose_name_plural': 'Bindata'},
        ),
        migrations.AlterModelOptions(
            name='checked',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='companies',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='concession',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='concessioncorners',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hccontent',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='operator',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='persons',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='provisional',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='psd',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='psd_datum',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rig',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='seismicsurvey',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='seismictype',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='seismicvintage',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='staked',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wellgeoinfo',
            options={'managed': True, 'verbose_name_plural': 'WellGeoinfo'},
        ),
        migrations.AlterModelOptions(
            name='wellstatus',
            options={'managed': True, 'verbose_name_plural': 'WellStatus'},
        ),
        migrations.AlterModelOptions(
            name='welltype',
            options={'managed': True},
        ),
    ]
