# Generated by Django 2.1.7 on 2019-08-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0004_auto_20190808_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checked',
            name='well_info',
            field=models.ForeignKey(blank=True, db_column='well_info_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.WellGeoinfo'),
        ),
        migrations.AlterField(
            model_name='staked',
            name='well_info',
            field=models.ForeignKey(blank=True, db_column='well_info_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='wells.WellGeoinfo'),
        ),
    ]
