# Generated by Django 2.1.7 on 2019-10-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0005_auto_20190808_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellgeoinfo',
            name='owner_original',
            field=models.ForeignKey(blank=True, db_column='owner_original', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='wells.Operator'),
        ),
    ]
