# Generated by Django 2.1.7 on 2019-10-14 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0006_wellgeoinfo_owner_original'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wellgeoinfo',
            name='operator',
            field=models.ForeignKey(blank=True, db_column='operator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='operator', to='wells.Operator'),
        ),
        migrations.AlterField(
            model_name='wellgeoinfo',
            name='owner_original',
            field=models.ForeignKey(blank=True, db_column='owner_original', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner_original', to='wells.Operator'),
        ),
    ]
