# Generated by Django 2.1.7 on 2019-10-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0007_auto_20191014_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellgeoinfo',
            name='uwi_exploration_shell',
            field=models.CharField(blank=True, db_column='uwi_exploration_shell', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wellgeoinfo',
            name='uwi_operation_shell',
            field=models.CharField(blank=True, db_column='uwi_operation_shell', max_length=255, null=True),
        ),
    ]
