# Generated by Django 2.1.7 on 2019-10-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0008_auto_20191014_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellgeoinfo',
            name='wims_name_shell',
            field=models.CharField(blank=True, db_column='wims_name_shell', max_length=255, null=True),
        ),
    ]
