# Generated by Django 2.1.7 on 2019-10-14 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0009_wellgeoinfo_wims_name_shell'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concession',
            name='arabicname',
        ),
    ]
