# Generated by Django 2.1.7 on 2019-10-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0011_auto_20191015_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production_field',
            name='field_name',
            field=models.CharField(blank=True, db_column='field_name', max_length=255, null=True),
        ),
    ]
