# Generated by Django 2.1.7 on 2019-10-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0013_auto_20191015_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='egpc_name',
            field=models.CharField(blank=True, db_column='egpc_name', max_length=255, null=True),
        ),
    ]
