# Generated by Django 2.1.7 on 2019-10-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0014_concession_egpc_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellgeoinfo',
            name='openworks_name',
            field=models.CharField(blank=True, db_column='openworks_name', max_length=255, null=True),
        ),
    ]
