# Generated by Django 2.1.7 on 2019-10-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0015_wellgeoinfo_openworks_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='wellgeoinfo',
            name='sap_functional_location',
            field=models.CharField(blank=True, db_column='sap_functional_location', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wellgeoinfo',
            name='sap_name',
            field=models.CharField(blank=True, db_column='sap_name', max_length=255, null=True),
        ),
    ]
