# Generated by Django 2.1.7 on 2019-10-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wells', '0016_auto_20191024_0841'),
    ]

    operations = [
        migrations.AddField(
            model_name='concession',
            name='field_name',
            field=models.CharField(blank=True, db_column='field_name', max_length=255, null=True),
        ),
    ]
