"""
Django settings for wells_access project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '44*f)(kymit!mx!m0=1q@iyo_x+1x9yl)gge!+%wd)v4wq9q1*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django_filters',
    'django_tables2',
    'cart',
    'users',
    'crispy_forms',
    'wells',
    'django_dms',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.gis',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 'django.contrib.auth.middleware.RemoteUserMiddleware',
    # 'django.contrib.auth.middleware.PersistentRemoteUserMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# AUTHENTICATION_BACKENDS = [
#     # 'django.contrib.auth.backends.RemoteUserBackend',
#     'django.contrib.auth.backends.ModelBackend',
# ]

ROOT_URLCONF = 'wells_access.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wells_access.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    # }

    # # #--------------------------------------------

    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'OPTIONS': {
    #         'options': '-c search_path=postgres,public'

    #     },

    #     # 'NAME': 'wells_test',
    #     'NAME': 'wells_access',
    #     'HOST': '192.168.142.109',
    #     'USER': 'postgres',
    #     'PASSWORD': 'yana',
    #     'PORT': '5432',
    # }

    # # # #--------------------------------------------
    # ---------------- esri_pg_geomatics
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        # 'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'OPTIONS': {
            'options': '-c search_path=wells_access,wells_geo,django'

        },

        # 'NAME': 'wells_test',
        'NAME': 'esri_pg_geomatics',
        'HOST': '192.168.142.109',
        'USER': 'postgres',
        'PASSWORD': 'yana',
        'PORT': '5432',
    }
    # ------------------------
    # ---------------- MS Access
    # 'default': {
    #     'ENGINE': 'access.pyodbc',
    #     'NAME': 'O:\Bapetco_GIS\XMT\Wells_DB\Backup_2019\Wells_DB.mdb',
    #     'USER': '',
    #     'PASSWORD': '',
    # }
    # ------------------------
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

DATE_FORMAT = "%d-%m-%Y"  # "yyyy-MM-dd" #"%d-%m-%Y" #"%d-%m-%Y"

DATE_INPUT_FORMATS = '%d/%m/%Y'  # ('%d-%m-%Y','%Y-%m-%d')

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'

# Added Code
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

CRISPY_TEMPLATE_PACK = 'bootstrap4'

LOGIN_REDIRECT_URL = 'bx-home'
LOGIN_URL = 'login'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'mail.bapetco.net'
# EMAIL_PORT = 587
EMAIL_PORT = 6004

EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'bapetco/ebnes0'
EMAIL_HOST_PASSWORD = ''
CART_SESSION_ID = 'cart'

# https://mail.bapetco.net/mapi/emsmdb/?MailboxId=1e510ac5-6f82-49a5-99e9-57b6fb06f6dc@bapetco.net

# N.El-Sisi@BAPETCO.NET
